### ISSUE TITLE
[Bug] tortoise_v2 support seems to have gone obsolete

### ISSUE THREAD

**Issue by Eclextic** [idiap/coqui-ai-TTS#388]
### Describe the bug

Tortoise has become unsupported and needs fixing. Something has gone obsolete and adding trust_remote_code=True to the args in tts.tts_to_file() doesn't fix it.

### To Reproduce

import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

tts = TTS("tts_models/en/multi-dataset/tortoise-v2").to(device)

tts.tts_to_file(
  text="""
Here's a comprehensive overview of World War 2: The conflict began on September first
nineteen thirty-nine when Germany, led by Adolf Hitler and the Nazi Party, invaded
Poland, prompting declarations of war from France and the United Kingdom.""",
    split_sentences=False,
    file_path="output1.wav",
)

### Expected behavior

For it to work.

### Logs

```shell
GPT2InferenceModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model classsuch that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'llget an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
 69%|███████████████████████████████████                | 11/16 [01:19<00:36,  7.24s/i 75%|██████████████████████████████████████▎            | 12/16 [01:27<00:29,  7.48s/i 81%|█████████████████████████████████████████▍         | 13/16 [01:34<00:22,  7.34s/i 88%|████████████████████████████████████████████▋      | 14/16 [01:42<00:15,  7.65s/i 94%|███████████████████████████████████████████████▊   | 15/16 [01:50<00:07,  7.58s/i100%|███████████████████████████████████████████████████| 16/16 [01:57<00:00,  7.43s/i100%|███████████████████████████████████████████████████| 16/16 [01:57<00:00,  7.33s/it]
  0%|               | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/tangerine-dev/coqui-tts/../coqui-tts-test.py", line 45, in <module>
    tts.tts_to_file(
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/api.py", line 374, in tts_to_file
    wav = self.tts(
          ^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/api.py", line 323, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/utils/synthesizer.py", line 422, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 539, in synthesize
    outputs = self.inference_with_config(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 609, in inference_with_config
    return self.inference(text, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 760, in inference
    clvp_res = clvp(
               ^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/TTS/tts/layers/tortoise/clvp.py", line 109, in forward
    text_emb = self.text_emb(text)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/home/tangerine-dev/coqui-tts/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060 Laptop GPU"
        ],
        "available": true,
        "version": "12.6"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.7.0+cu126",
        "TTS": "0.26.1",
        "numpy": "2.2.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.12.10",
        "version": "#1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000"
    }
}
```

**Comment by eginhard** [comment]
Thank you for the report, I can reproduce the issue. A PR for this would be very welcome, I probably won't have time to look into it anytime soon.

Note that the initial warning about generative capabilities is unrelated.

**Comment by 9throok** [comment]
Shit.. i came here for a solution TBH. @Eclextic did you get any success?

If not, i could be able to look into it.

**Comment by Eclextic** [comment]
Nope. I have actually decided to switch to Kokoro-TTS which in my honest opinion sounds much better, doesn't have background noise, sounds like Siri and doesn't hallucinate or have problems with newlines or punctuation while also being a really small and low latency real-time model. (82M parameters)

So yea as you can see, I kinda don't care anymore XD

Go for it! Maybe I will try out tortoise later when this works again...

**Comment by btseee** [comment]
Hi @Eclextic ,

I had never used tortoise before but it looks like same issue that i had with Forward models:
I fixed it by:  https://github.com/idiap/coqui-ai-TTS/pull/378/files

And i hope it will give you some ideas.

**Comment by Eclextic** [comment]
@btseee Ah alr, so the same problems persist that other models have with noise and hallucinations? I mean what did I expect, the training technic is still the same like XTTS_V2 etc...

**Comment by Eclextic** [comment]
> Hi @Eclextic ,
> 
> I had never used tortoise before but it looks like same issue that i had with Forward models:
> I fixed it by:  https://github.com/idiap/coqui-ai-TTS/pull/378/files
> 
> And i hope it will give you some ideas.

Forgot to say lmao, thank you for your contribution nonetheless. I will try it out shortly myself.

**Comment by Eclextic** [comment]
> Hi @Eclextic ,
> 
> I had never used tortoise before but it looks like same issue that i had with Forward models:
> I fixed it by:  https://github.com/idiap/coqui-ai-TTS/pull/378/files
> 
> And i hope it will give you some ideas.

Forgot to say lmao, thank you for your contribution nonetheless. I will try it out shortly myself.

**Comment by Eclextic** [comment]
@btseee I have a Multi-GPU setup which seems to trip up tortoise:

```
Traceback (most recent call last):
  File "/home/tangerine-dev/Documents/FlairAI/coqui-tts-test.py", line 103,in <module>
    wav = tts.tts(
          ^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/api.py", line 323, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/utils/synthesizer.py", line 422, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 539, in synthesize
    outputs = self.inference_with_config(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 609, in inference_with_config
    return self.inference(text, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/tts/models/tortoise.py", line 760, in inference
    clvp_res = clvp(
               ^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/TTS/tts/layers/tortoise/clvp.py", line 109, in forward
    text_emb = self.text_emb(text)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/home/tangerine-dev/Documents/FlairAI/.venv/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument indexin method wrapper_CUDA__index_select)
```

**Comment by Eclextic** [comment]
Although it seems that this is more a cuda and cpu problem... and not a multi-GPU problem.

**Comment by btseee** [comment]
@Eclextic have you tried to move every submodule to your device

like :
```
tts.synthesizer.tts_model.to(device)
tts.synthesizer.vocoder_model.to(device)
```

**Comment by Eclextic** [comment]
Wait fuck... I might have not updated it correctly in a rush, hold on... I think I used the PyPi version instead of Git...

**Comment by Eclextic** [comment]
Nope, still the same problem, even with:

> [@Eclextic](https://github.com/Eclextic) have you tried to move every submodule to your device
> 
> something like :
> 
> ```
> tts.synthesizer.tts_model.to(device)
> tts.synthesizer.vocoder_model.to(device)
> tts.synthesizer.tts_config.clvp_model.to(device)
> ```

Because of essentially vocoder_model and co not actually existing...
```
    tts.synthesizer.vocoder_model.to("cuda")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'
```
